from src.plotting.scaling import plot_scaling_experiment
from src.plotting.scaling_higher_length import plot_scaling_higher_length_experiment
from src.plotting.tradeoff import plot_tradeoff_4_experiment, plot_tradeoff_main_experiment
from src.plotting.generalization import plot_generalization_experiment
from src.plotting.scratchpad import plot_scratchpad_experiment
from src.plotting.dynamic import plot_dynamic_100k_experiment, plot_dynamic_main_experiment